### ISSUE TITLE
Support for Zepto.js

### ISSUE THREAD

**Issue by gunta** [mattbradley/livestampjs#1]
Hi! 

I've been playing with the library and it's really simple and something I was planning to make before!

As I'm developing for mobile (iPhone/Android), the cost of including jQuery is prohibitive, so instead I'm using Zepto.js, so I would like to ask just support for it! Shouldn't really be that difficult ;)

http://zeptojs.com/

Thank you!
Gunther

**Comment by mattbradley** [comment]
That's not a bad idea, and I might look into that.

In the mean time, keep in mind that most mobile browsers have caches just like desktop browsers. So if you include jQuery from a widely-used content delivery network, your users may already have jQuery cached on their devices. You can use Google's CDN like this:

```
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
```

Check out [3 reasons why you should let Google host jQuery for you](http://encosia.com/3-reasons-why-you-should-let-google-host-jquery-for-you/) for more info.

**Comment by gunta** [comment]
Hi! Thank you for your reply.

Yes I know about the Google CDNs ;)
The real problem here is not just the bandwidth, (jQuery is around 100kb whereas Zepto is around 25kb),
the problem is the JavaScript parsing performance impact on the CPU/memory.

Remember that on mobile the CPU is a lot weaker than on desktop, so parsing those jQuery 100kb on each page load adds around 1~2 seconds to the initial load.

**Comment by dinacel** [comment]
Pull request https://github.com/mattbradley/livestampjs/pull/8 closes this issue.
