### ISSUE TITLE
Add customizable interval

### ISSUE THREAD

**Issue by beaumartinez** [mattbradley/livestampjs#10]
Once a minute is a sensible default, but I'd like it to be customizable as well—so we could update every five seconds on more "time-sensitive" data, for example.

**Comment by mattbradley** [comment]
It's not documented, but you can do this with the global `interval()` function. `$.livestamp.interval()` will return the current interval in seconds. `$.livestamp.interval(x)` will set the interval to `x` seconds.

**Comment by beaumartinez** [comment]
That's pretty sweet. Perhaps you should add it to the documentation?

Awesome project BTW.

**Comment by 97jaz** [comment]
I'm not sure if commenting on a closed issue is a great idea, but...
From looking at the code, it appears that the interval (unlike timestamps) are specified in milliseconds, not seconds. So the default behavior is to update once per second, not once per minute. And calling interval(x) sets the interval to x milliseconds. But maybe I'm missing something?
