### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by sgarbesi** [mattbradley/livestampjs#12]
Probably will help gain some popularity and also be useful if you added this.

http://cdnjs.com/

**Comment by ian-kent** [comment]
anyone can add libraries to cdnjs - https://github.com/cdnjs/cdnjs

**Comment by ghidinelli** [comment]
I went and did this just now: https://github.com/cdnjs/cdnjs/pull/2747

**Comment by ghidinelli** [comment]
This has been completed: https://github.com/cdnjs/cdnjs/commit/7e97a953b66ba6ddc9df6e1319f00ab0791d23e1  

I presume it will show up on the cdn shortly.
