### ISSUE TITLE
Multi Lingual version

### ISSUE THREAD

**Issue by macray125** [mattbradley/livestampjs#18]
Hi Sir,

Can you help me on how to convert this into Multi lingual languages

Thanks.

**Comment by mattbradley** [comment]
Livestamp.js uses Moment.js to generate all of the time-ago text, so it is compatible with Moment's language support. Check out [Moment's internationalization documentation](http://momentjs.com/docs/#/i18n/) to get Moment working with other languages.

**Comment by crapthings** [comment]
awesome to see this. @mattbradley

**Comment by pangui** [comment]
I'm having trouble setting moment.locale **before** livestamp replaces DOM elements (with data-livestamp). My intention is to do something like this:

```
moment.locale($('body').data('lang'));
```

I have checked both livestamp and moment documentation but I can't find the way to do it. Thanks a lot!

**Comment by leap-it** [comment]
pangui what i did is load the moment.js first (not the moment with locals)
then i load the fr.js (thats right i created a file for each language  fr.js en-gb.js etc...)
then i load the livestamp.js
 this works for me.

ps i downloaded this file which contains a folder with most langugue files already in them :)
http://fullcalendar.io/download/

**Comment by pangui** [comment]
Thank you @leap-it I'm going to try your suggestion
