### ISSUE TITLE
data-livestamp attribute can't be written to by Knockout JS

### ISSUE THREAD

**Issue by Soviut** [mattbradley/livestampjs#2]
Here's the issue I submitted to the Knockout repository:

https://github.com/SteveSanderson/knockout/issues/697

Basically, Knockout uses a `data-bind` attribute but looks for it using a regex that finds all attributes beginning with `data-`. This causes a conflict when trying to have knockout generate a `data-livestamp` attribute on an element.

I worked around it by creating what's known as a custom binding that has access to the raw element and can apply the attributes and `livestamp()` directly.

This might be a good reason to allow a attribute name option in to be specified when calling livestamp to avoid conflicts.

**Comment by gordol** [comment]
```html
<span data-bind="attr: {'data-livestamp': receive_timestamp}">19 minutes ago</span>
```

**Comment by philfreo** [comment]
according to the comments from that other thread, it doesn't sound like there's an actual issue here (in either repo)
