### ISSUE TITLE
Livestamp on Chrome

### ISSUE THREAD

**Issue by averj** [mattbradley/livestampjs#23]
Hello,
I recently tried to implement Livestamp on my site (the simplest task) and it didn't appear to work when testing it.  After debugging it and using different browsers I noticed it worked on Safari and not Chrome.
Chrome:
![screen shot 2014-04-19 at 10 57 53 am](https://cloud.githubusercontent.com/assets/6731369/2748730/08887042-c7d3-11e3-8541-c0fb628362be.png)
Safari:
![screen shot 2014-04-19 at 10 56 18 am](https://cloud.githubusercontent.com/assets/6731369/2748731/09c05858-c7d3-11e3-9465-b166769b5b6a.png)

I thought this was weird because your github.io site worked fine with it. I also was able to have someone replicate the same result. Am I doing something wrong?  Thanks,
Julien.

**Comment by mattbradley** [comment]
Are you getting any errors in the developer tools console?

**Comment by averj** [comment]
My apologies, it appears Github disabled hot-linking to files and Chrome respected that, Safari on the other hand did not.  Thank you for your time.
