### ISSUE TITLE
display and update dynamically created <span data-livestamp=''> element

### ISSUE THREAD

**Issue by dongliu** [mattbradley/livestampjs#27]
On a page, <span data-livestamp=''> elements are dynamically created and appended to the dom. They are not properly displayed or updated. I tried to call $.livestamp.update() or $.livestamp.resume() right after the dom operation, and it did not work.

**Comment by mattbradley** [comment]
I'm having trouble reproducing this bug. Can you make an example on http://jsfiddle.net?

**Comment by dongliu** [comment]
I double checked the code, and found the problem was because the time string format. I read through the document and found only seconds or ISO 8601 are allowed within data-livestamp. After formatting the time string with moment, livestamp works as expected. In fact, I think any format accepted by moment should work after I go through the source code.
