### ISSUE TITLE
No livestamp when used together with Angular?

### ISSUE THREAD

**Issue by bobbyware** [mattbradley/livestampjs#29]
I've the following HTML:

```
<span data-livestamp="{{summaryItem.created}}"></span>
```

Created is a number in seconds, e.g. '1412451961'. However, the resulting span is just empty?

If I put this hardcoded in the template:

```
<span data-livestamp="1412451961"></span>
```

It works... 
Not sure why this is not working?

**Comment by AndersDJohnson** [comment]
Probably Livestamp is auto-initializing before your angular `$scope` is initialized and the expression gets a value.

Try calling `$('#selector').livestamp()` again after variable is set in your `$scope`. You could try a `$watch` also:

``` js
$scope.$watch('summaryItem.created', function () {
  $('#selector').livestamp();
});
```

It might be worth finding or creating a custom directive.

Alternatively, you could try:
- https://github.com/urish/angular-moment
- https://uttesh.github.io/ngtimeago/

**Comment by bobbyware** [comment]
Thanks, the $watch did not work first time, I tried angular-moment and that's working perfectly.
It's weird though, it used to work with Livestamp. Not sure why not anymore.
