### ISSUE TITLE
Setting data-livestamp to null should remove it?

### ISSUE THREAD

**Issue by CubedEye** [mattbradley/livestampjs#3]
Hi,

This is an enhancement that may have other uses in other libraries.

We are currently using timestamp with Backbone.Modelbinder, and it's working better than expected with a converter we have written. It looks something like this:

``` javascript
livestamp = function (direction, value, attribute, model) {
        var field = $(this.boundEls[0]).attr('data-model-field');
        var modelField = model.get(field);
        if(modelField && typeof modelField.toISOString === 'function'){
            return modelField.toISOString();
        } else {
            $(this.boundEls[0]).livestamp('destroy');
        }
    };
```

It would be nice if livestamp could destroy itself if the `data-livestamp` attribute was set to null or something similar. Instead of having `$(this.boundEls[0]).livestamp('destroy');`.

**Comment by philfreo** [comment]
I've never heard of any other jQuery plugins performing in that way, and I'm not even sure that there's a performant way to observe/detect when the data-livestamp attribute is cleared. Let us know if you have examples or more info on how this would make sense.
