### ISSUE TITLE
[question] convert to full timeago "x years, y months, z days ago" not only "years/months/days" ago

### ISSUE THREAD

**Issue by flashios09** [mattbradley/livestampjs#35]
Hi,
Thanks @adjohnson916  for this awesome jquery plugin :+1: 
Sorry for my bad english :(

Is it possible to convert a datetime to **full timeago** like this
**2015-01-25 03:37:46** to "**2 months, one day, 5 hours and 10 minutes ago**"

now it only convert **2015-01-25 03:37:46** to "**2 months ago**"

Thanks

**Comment by AndersDJohnson** [comment]
@flashios09  - It's not my plugin, it's primarily @mattbradley's!

We rely on [Moment.js](http://momentjs.com/) for this functionality ([moment#fromNow](http://momentjs.com/docs/#/displaying/fromnow/)), and it looks like they don't support this. So could instead file an issue there and let us know?

Thanks!
