### ISSUE TITLE
Time ago is off for me?

### ISSUE THREAD

**Issue by whoacowboy** [mattbradley/livestampjs#52]
I am working with this
date: **2015-12-23 01:30:23**.
seconds: **1450834223**

Using [Carbon](https://github.com/briannesbitt/Carbon) in php I get **1 month ago**
`<? $user->created_at->diffForHumans() ?>`

Using livestamp I get **2 months ago**
`<span data-livestamp="1450834223"></span>`

I may be doing something worng. I made this test and it all came out ass backwards.
[Codepen](http://codepen.io/whoacowboy/pen/jWRKev?editors=1111)

**Comment by fabslab** [comment]
December is 2 months ago.

**Comment by whoacowboy** [comment]
December 23rd is one month and 24 days ago.

**Comment by mattbradley** [comment]
That date is between 1 and 2 months ago. My guess is it has something to do with the difference between how Carbon and Momentjs do rounding. Carbon probably floors down to 1 month, and Momentjs probably rounds up to 2 months.

**Comment by whoacowboy** [comment]
Checkout my [Codepen](http://codepen.io/whoacowboy/pen/jWRKev?editors=1111), I am getting some vey odd results.

I kind of recon it to birthdays, my son is 5 and 3/4 not six.

**Comment by mattbradley** [comment]
What is odd about the results?

**Comment by whoacowboy** [comment]
It does look like livestamp is rounding up the timestamp to the nearest unit. 

`$('#feb-2000').livestamp(new Date('February 1, 2000'));`
16 years, 16 days excluding the end date
result **16 years ago**

`$('#mar-2000').livestamp(new Date('March 1, 2000'));`
15 years, 11 months, 16 days excluding the end date
result **16 years ago**

`$('#sep-2000').livestamp(new Date('September 1, 2000'));`
15 years, 05 months, 16 days excluding the end date
result **15 years ago**

I think that works nicely in most situations, but when dealing with time I believe it goes against our general understanding when you get to larger units (months/years).

Rounding up 31 seconds ago to a minutes, feels appropriate, who cares, but when we get to years it feels a little weird. 

Like I mentioned, my son isn't 6 years old, he is 5 3/4 and he and all of his friends will correct you if you say he is six. 

I'd like to recommend one of two options, the first would be to make it acurate to the actual time passed, use `floor` not `ceil`.

The second would be to provide a parameter, round: 'up'/'down'

**Comment by mattbradley** [comment]
The timeago and rounding calculations are handled by Momentjs. [The docs](http://momentjs.com/docs/#/displaying/fromnow/) show how each timespan is displayed. It would be best to open an issue on [the Momentjs repo](https://github.com/moment/moment/) if you'd like to see this change.

**Comment by whoacowboy** [comment]
Cool thanks!
