### ISSUE TITLE
error  giving relative time

### ISSUE THREAD

**Issue by ashishpandey2013** [mattbradley/livestampjs#9]
its  displaying 
in 5 hours  in  my project
my  timesozone is 'Aisa/Calcutta'

**Comment by mattbradley** [comment]
I need a little more information. What text were you expecting it to display? What timestamp did you use?

**Comment by ashishpandey2013** [comment]
sorry  my  bad  my  server  was  in the  wrong timezone
.please  pull that  of ,that thing is  solved now!!!

**Comment by ashishpandey2013** [comment]
pease  close this Isssue,Its  working fine now!!!!
